# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0019_prevalence_of_overweight_and_obesity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Households_Owned_Ict_Equipment_Services',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('computer', models.DecimalField(decimal_places=1, max_digits=10)),
                ('television', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Households_With_Internet_By_Type',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('fixed_wired', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fixed_wireless', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mobile_broadband', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mobile', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Households_With_Tv',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('digital_tv', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pay_tv', models.DecimalField(decimal_places=1, max_digits=10)),
                ('free_to_air', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ip_tv', models.DecimalField(decimal_places=1, max_digits=10)),
                ('none', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Households_Without_Internet_By_Reason',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('dont_need', models.DecimalField(decimal_places=1, max_digits=10)),
                ('lack_skills', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_network', models.DecimalField(decimal_places=1, max_digits=10)),
                ('access_elsewhere', models.DecimalField(decimal_places=1, max_digits=10)),
                ('doesnt_meet_needs', models.DecimalField(decimal_places=1, max_digits=10)),
                ('service_cost_high', models.DecimalField(decimal_places=1, max_digits=10)),
                ('equipment_cost_high', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cultural_reasons', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other_reasons', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_Above18By_ReasonNotHaving_Phone',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('too_young', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dont_need', models.DecimalField(decimal_places=1, max_digits=10)),
                ('restricted', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_network', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender_bias', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_electricity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('phone_expe', models.DecimalField(decimal_places=1, max_digits=10)),
                ('maintain_expe', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_Above18Subscribed_MobileMoney',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_money', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mobile_banking', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_By_IctEquipment_And_ServicesUsed',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('television', models.DecimalField(decimal_places=1, max_digits=10)),
                ('radio', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mobile', models.DecimalField(decimal_places=1, max_digits=10)),
                ('computer', models.DecimalField(decimal_places=1, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_That_DidntUseInternet_By_Reason',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('too_young', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dont_need', models.DecimalField(decimal_places=1, max_digits=10)),
                ('lack_skill', models.DecimalField(decimal_places=1, max_digits=10)),
                ('expensive', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_internet', models.DecimalField(decimal_places=1, max_digits=10)),
                ('culture', models.DecimalField(decimal_places=1, max_digits=10)),
                ('control', models.DecimalField(decimal_places=1, max_digits=10)),
                ('security', models.DecimalField(decimal_places=1, max_digits=10)),
                ('others', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_That_Used_Internet_By_Purpose',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('seek_info', models.DecimalField(decimal_places=1, max_digits=10)),
                ('make_app', models.DecimalField(decimal_places=1, max_digits=10)),
                ('get_info', models.DecimalField(decimal_places=1, max_digits=10)),
                ('newspaper', models.DecimalField(decimal_places=1, max_digits=10)),
                ('banking', models.DecimalField(decimal_places=1, max_digits=10)),
                ('voip', models.DecimalField(decimal_places=1, max_digits=10)),
                ('selling', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ordering', models.DecimalField(decimal_places=1, max_digits=10)),
                ('course', models.DecimalField(decimal_places=1, max_digits=10)),
                ('research', models.DecimalField(decimal_places=1, max_digits=10)),
                ('informative', models.DecimalField(decimal_places=1, max_digits=10)),
                ('write_article', models.DecimalField(decimal_places=1, max_digits=10)),
                ('social_nets', models.DecimalField(decimal_places=1, max_digits=10)),
                ('movie', models.DecimalField(decimal_places=1, max_digits=10)),
                ('search_work', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_Who_Used_Internet_By_Place',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobility', models.DecimalField(decimal_places=1, max_digits=10)),
                ('work', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cyber', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ed_centre', models.DecimalField(decimal_places=1, max_digits=10)),
                ('comm_centre', models.DecimalField(decimal_places=1, max_digits=10)),
                ('another_home', models.DecimalField(decimal_places=1, max_digits=10)),
                ('at_home', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Population_WithMobilePhone_AndAverageSims',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('avg_sims', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population_sims', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
