# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0023_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Hholds_By_Habitable_Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('one', models.DecimalField(decimal_places=1, max_digits=10)),
                ('two', models.DecimalField(decimal_places=1, max_digits=10)),
                ('three', models.DecimalField(decimal_places=1, max_digits=10)),
                ('four', models.DecimalField(decimal_places=1, max_digits=10)),
                ('five', models.DecimalField(decimal_places=1, max_digits=10)),
                ('six_plus', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mean_rooms', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('persons_per_room', models.DecimalField(decimal_places=1, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Hholds_By_Housing_Tenure',
            fields=[
                ('tenure_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_occupier', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pays_rent', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_rent_consent', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_rent_squatting', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Hholds_By_Type_Of_Housing_Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('bungalow', models.DecimalField(decimal_places=1, max_digits=10)),
                ('flat', models.DecimalField(decimal_places=1, max_digits=10)),
                ('maisonnette', models.DecimalField(decimal_places=1, max_digits=10)),
                ('swahili', models.DecimalField(decimal_places=1, max_digits=10)),
                ('shanty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('manyatta', models.DecimalField(decimal_places=1, max_digits=10)),
                ('landhi', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Hholds_In_Rented_Dwellings',
            fields=[
                ('dwelling_id', models.AutoField(primary_key=True, serialize=False)),
                ('govt_national', models.DecimalField(decimal_places=1, max_digits=10)),
                ('govt_county', models.DecimalField(decimal_places=1, max_digits=10)),
                ('parastatal', models.DecimalField(decimal_places=1, max_digits=10)),
                ('company_directly', models.DecimalField(decimal_places=1, max_digits=10)),
                ('company_agent', models.DecimalField(decimal_places=1, max_digits=10)),
                ('individual_directly', models.DecimalField(decimal_places=1, max_digits=10)),
                ('individual_agent', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Main_Roofing_Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('grass', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mud', models.DecimalField(decimal_places=1, max_digits=10)),
                ('iron_sheets', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tin_cans', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sheet', models.DecimalField(decimal_places=1, max_digits=10)),
                ('concrete', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tiles', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Main_Wall_Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('lime_stone', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bricks', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cement_blocks', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cement_finish', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wood', models.DecimalField(decimal_places=1, max_digits=10)),
                ('adobe', models.DecimalField(decimal_places=1, max_digits=10)),
                ('iron_sheets', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bamboo', models.DecimalField(decimal_places=1, max_digits=10)),
                ('stone', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cane', models.DecimalField(decimal_places=1, max_digits=10)),
                ('plywood', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Owner_Occupier_Dwellings',
            fields=[
                ('dwelling_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchased_cash', models.DecimalField(decimal_places=1, max_digits=10)),
                ('purchased_loan', models.DecimalField(decimal_places=1, max_digits=10)),
                ('purchased_cash_loan', models.DecimalField(decimal_places=1, max_digits=10)),
                ('constructed_cash', models.DecimalField(decimal_places=1, max_digits=10)),
                ('constructed_loan', models.DecimalField(decimal_places=1, max_digits=10)),
                ('constructed_cash_loan', models.DecimalField(decimal_places=1, max_digits=10)),
                ('inherited', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gift', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bartered', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
