# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_sectors'),
        ('Housing_Conditions', '0002_kihibs_main_floor_material_kihibs_main_source_of_drinking_water_kihibs_main_source_of_lighting_fuel_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Main_Source_Of_Cooking_Fuel',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('firewood', models.DecimalField(decimal_places=1, max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('lpg', models.DecimalField(decimal_places=1, max_digits=10)),
                ('biogas', models.DecimalField(decimal_places=1, max_digits=10)),
                ('kerosene', models.DecimalField(decimal_places=1, max_digits=10)),
                ('charcoal', models.DecimalField(decimal_places=1, max_digits=10)),
                ('shrubs', models.DecimalField(decimal_places=1, max_digits=10)),
                ('animal_dung', models.DecimalField(decimal_places=1, max_digits=10)),
                ('crop_residue', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Primary_Type_Of_Cooking_Appliance',
            fields=[
                ('appliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('stone_fire', models.DecimalField(decimal_places=1, max_digits=10)),
                ('imp_stone_fire', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ordinary_jiko', models.DecimalField(decimal_places=1, max_digits=10)),
                ('improved_jiko', models.DecimalField(decimal_places=1, max_digits=10)),
                ('stove', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gas_cooker', models.DecimalField(decimal_places=1, max_digits=10)),
                ('electric_cooker', models.DecimalField(decimal_places=1, max_digits=10)),
                ('elec_gas_cooker', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
