# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0022_kihibs_children_by_additional_supplement_kihibs_children_by_place_of_delivery_kihibs_children_by_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption_Expenditure_And_Quintile_Distribution',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('mean', models.IntegerField()),
                ('median', models.IntegerField()),
                ('quarter1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution_Of_Household_Food_Consumption',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchases', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('own_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gifts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Distribution_Of_Households_By_Point_Of_Purchased_Food_Items',
        #     fields=[
        #         ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('supermarket', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('open_market', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('kiosk', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('general_shop', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('specialised_shop', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('informal_sources', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('other_formal_points', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('number_of_observations', models.IntegerField()),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Food_And_Non_Food_Expenditure_Per_Adult_Equivalent',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Estimates_By_Residence_And_County',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('headcount_rate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('distribution_of_the_poor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('poverty_gap', models.DecimalField(decimal_places=1, max_digits=10)),
                ('severity_of_poverty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('number_of_poor', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Hardcore_Estimates_By_residence_And_County',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('headcount_rate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('distribution_of_the_poor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('poverty_gap', models.DecimalField(decimal_places=1, max_digits=10)),
                ('severity_of_poverty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('number_of_poor', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Overall_Estimates_By_Residence_And_County',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('headcount_rate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('distribution_of_the_poor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('poverty_gap', models.DecimalField(decimal_places=1, max_digits=10)),
                ('severity_of_poverty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('population', models.IntegerField()),
                ('number_of_poor', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
