# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0022_kihibs_children_by_additional_supplement_kihibs_children_by_place_of_delivery_kihibs_children_by_who'),
        ('Poverty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_Of_Households_By_PointOfPurchasedFoodItems',
            fields=[
                ('poverty_id', models.AutoField(primary_key=True, serialize=False)),
                ('supermarket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_market', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kiosk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_shop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialised_shop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informal_sources', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_formal_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_observations', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
