# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0023_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household_Kihibs_Households_That_Sought_Credit',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_sought', models.DecimalField(decimal_places=1, max_digits=10)),
                ('households', models.IntegerField()),
                ('h_a_sought', models.DecimalField(decimal_places=1, max_digits=10)),
                ('hholds_sought', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
