# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0022_kihibs_children_by_additional_supplement_kihibs_children_by_place_of_delivery_kihibs_children_by_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Children_By_Breastfeeding_Status',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('ever_breastfed', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_children', models.IntegerField()),
                ('one_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('one_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ch_breastfed', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_By_First_Food_Supplement',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('other_milk', models.DecimalField(decimal_places=1, max_digits=10)),
                ('infant_food', models.DecimalField(decimal_places=1, max_digits=10)),
                ('porridge', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fort_porridge', models.DecimalField(decimal_places=1, max_digits=10)),
                ('semi_solids', models.DecimalField(decimal_places=1, max_digits=10)),
                ('water', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_children', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_In_Community_Nutrition_Programmes',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('participated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_participated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_children', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_In_Growth_Monitoring_Programmes',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('participated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_participated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_children', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Dutation_Of_Breastfeeding',
            fields=[
                ('duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('breastfeeding', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mean', models.DecimalField(decimal_places=1, max_digits=10)),
                ('median', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Undernourished_Children',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('height_for_age', models.DecimalField(decimal_places=1, max_digits=10)),
                ('weight_for_age', models.DecimalField(decimal_places=1, max_digits=10)),
                ('weight_for_height', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_children', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
