# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_kihibs_incidence_of_sickness_injury_kihibs_reported_being_sick_injured_by_type_of_sickness_kihibs_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Disability_By_Type',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('visual', models.DecimalField(decimal_places=1, max_digits=10)),
                ('hearing', models.DecimalField(decimal_places=1, max_digits=10)),
                ('speech', models.DecimalField(decimal_places=1, max_digits=10)),
                ('physical', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mental', models.DecimalField(decimal_places=1, max_digits=10)),
                ('self_care', models.DecimalField(decimal_places=1, max_digits=10)),
                ('others', models.DecimalField(decimal_places=1, max_digits=10)),
                ('any_disability', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_disability', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Received_Free_Medical_Services',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_distribution', models.DecimalField(decimal_places=1, max_digits=10)),
                ('service_type', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Reported_Being_Sick_Injured_By_Cause',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_distribution', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cause', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='kihibs_reported_sickness_by_health_provider',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_distribution', models.DecimalField(decimal_places=1, max_digits=10)),
                ('health_provider', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Reported_Sickness_By_No_Of_Days_Missed',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_days', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Type_Of_Health_Care_Sought',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('curative', models.DecimalField(decimal_places=1, max_digits=10)),
                ('promotive_preventive', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Who_Diagnosed_Illness_Injury',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_worker', models.DecimalField(decimal_places=1, max_digits=10)),
                ('traditional_healer', models.DecimalField(decimal_places=1, max_digits=10)),
                ('non_household_member', models.DecimalField(decimal_places=1, max_digits=10)),
                ('self', models.DecimalField(decimal_places=1, max_digits=10)),
                ('herbalist', models.DecimalField(decimal_places=1, max_digits=10)),
                ('faith_healer', models.DecimalField(decimal_places=1, max_digits=10)),
                ('household_member', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
