# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_kihibs_disability_by_type_kihibs_received_free_medical_services_kihibs_reported_being_sick_injured_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihibs_Children_By_Additional_Supplement',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('zinc_solution', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sugar_salt_solution', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other_solutions', models.DecimalField(decimal_places=1, max_digits=10)),
                ('none', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_By_Place_Of_Delivery',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.DecimalField(decimal_places=1, max_digits=10)),
                ('health_centre', models.DecimalField(decimal_places=1, max_digits=10)),
                ('clininc_dispensary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('maternity_home', models.DecimalField(decimal_places=1, max_digits=10)),
                ('at_home', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_By_Who_Assisted_At_Birth',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('midwife_nurse', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tba', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ttba', models.DecimalField(decimal_places=1, max_digits=10)),
                ('self', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_Immmunized_Against_Measles',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('measles_vaccination', models.CharField(max_length=50)),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Children_That_Had_Diarrhoea',
            fields=[
                ('proportion_id', models.AutoField(primary_key=True, serialize=False)),
                ('yes', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Disability_That_Had_Difficulty',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('yes', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no', models.DecimalField(decimal_places=1, max_digits=10)),
                ('dont_know', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Health_Insurance_Cover_By_Type',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('nhif', models.DecimalField(decimal_places=1, max_digits=10)),
                ('private_contributory', models.DecimalField(decimal_places=1, max_digits=10)),
                ('private_non_contributory', models.DecimalField(decimal_places=1, max_digits=10)),
                ('employee_contributory', models.DecimalField(decimal_places=1, max_digits=10)),
                ('employee_non_contributory', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Type_Of_Fluid_Of_Food_Given_During_Diarrhoea',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('nothing', models.DecimalField(decimal_places=1, max_digits=10)),
                ('breastmilk', models.DecimalField(decimal_places=1, max_digits=10)),
                ('porridge', models.DecimalField(decimal_places=1, max_digits=10)),
                ('water_alone', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other_milk', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Kihibs_Type_Of_Food_Given_During_Diarrhoea',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('nothing', models.DecimalField(decimal_places=1, max_digits=10)),
                ('commercial', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other_semi_solid', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fruits', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
